from fastapi import APIRouter

router = APIRouter()

COUNTERS= { #dicionario de desvantagens
    # --- TOP LANE ---
    "Aatrox": ["Fiora", "Camille", "Jax"],
    "Camille": ["Malphite", "Quinn", "Teemo"],
    "Cho'Gath": ["Vayne", "Fiora", "Kayle"],
    "Darius": ["Teemo", "Kayle", "Quinn"],
    "Dr. Mundo": ["Gwen", "Vayne", "Olaf"],
    "Fiora": ["Malphite", "Quinn", "Teemo"],
    "Gangplank": ["Camille", "Irelia", "Jax"],
    "Garen": ["Darius", "Fiora", "Quinn"],
    "Gnar": ["Camille", "Jayce", "Irelia"],
    "Gwen": ["Kayle", "Quinn", "Vayne"],
    "Illaoi": ["Teemo", "Quinn", "Vayne"],
    "Irelia": ["Malphite", "Garen", "Sett"],
    "Jax": ["Malphite", "Quinn", "Teemo"],
    "Jayce": ["Malphite", "Irelia", "Camille"],
    "Kayle": ["Irelia", "Renekton", "Darius"],
    "Kennen": ["Malphite", "Sion", "Ornn"],
    "Kled": ["Malphite", "Quinn", "Teemo"],
    "K'Sante": ["Fiora", "Camille", "Gwen"],
    "Malphite": ["Vayne", "Kayle", "Teemo"],
    "Mordekaiser": ["Fiora", "Camille", "Gwen"],
    "Nasus": ["Teemo", "Quinn", "Vayne"],
    "Olaf": ["Malphite", "Camille", "Quinn"],
    "Ornn": ["Camille", "Darius", "Gwen"],
    "Pantheon": ["Malphite", "Teemo", "Quinn"],
    "Poppy": ["Fiora", "Camille", "Garen"],
    "Quinn": ["Malphite", "Garen", "Sion"],
    "Renekton": ["Teemo", "Quinn", "Kayle"],
    "Riven": ["Malphite", "Garen", "Quinn"],
    "Rumble": ["Jayce", "Quinn", "Kayle"], 
    "Sett": ["Darius", "Garen", "Quinn"],
    "Shen": ["Camille", "Fiora", "Gwen"],
    "Singed": ["Teemo", "Quinn", "Vayne"],
    "Sion": ["Camille", "Darius", "Fiora"],
    "Tahm Kench": ["Fiora", "Camille", "Gwen"],
    "Teemo": ["Malphite", "Quinn", "Sion"],
    "Tryndamere": ["Malphite", "Quinn", "Teemo"],
    "Trundle": ["Teemo", "Quinn", "Kayle"], 
    "Urgot": ["Camille", "Fiora", "Garen"],
    "Volibear": ["Fiora", "Camille", "Darius"],
    "Yorick": ["Teemo", "Quinn", "Camille"],
    "Ambessa":  ["Darius", "Fiora", "Garen"],

    # --- MID LANE ---
    "Ahri": ["LeBlanc", "Zed", "Talon"],
    "Akali": ["Lissandra", "Annie", "Morgana"],
    "Akshan": ["Irelia", "Zed", "Malphite"], 
    "Anivia": ["Fizz", "Katarina", "Zed"],
    "Annie": ["Xerath", "Ziggs", "Vel'Koz"],
    "Aurelion Sol": ["Fizz", "LeBlanc", "Talon"],
    "Aurora": ["LeBlanc", "Zed", "Fizz"],
    "Azir": ["Zed", "LeBlanc", "Talon"],
    "Cassiopeia": ["Anivia", "Swain", "Viktor"],
    "Corki": ["Zed", "LeBlanc", "Fizz"],
    "Diana": ["Zed", "Talon", "Fizz"],
    "Ekko": ["Zed", "Talon", "LeBlanc"],
    "Fizz": ["Annie", "Lissandra", "Vex"],
    "Galio": ["Kassadin", "Veigar", "Viktor"],
    "Heimerdinger": ["Xerath", "Ziggs", "Syndra"], 
    "Hwei": ["Fizz", "Zed", "LeBlanc"],
    "Kassadin": ["Talon", "Zed", "Fizz"],
    "Katarina": ["Lissandra", "Annie", "Malzahar"],
    "LeBlanc": ["Annie", "Lissandra", "Malzahar"],
    "Lissandra": ["Xerath", "Ziggs", "Vel'Koz"], 
    "Malzahar": ["LeBlanc", "Zed", "Talon"],
    "Naafiri": ["Lissandra", "Annie", "Malzahar"],
    "Neeko": ["Zed", "Fizz", "Katarina"],
    "Orianna": ["Zed", "LeBlanc", "Fizz"],
    "Qiyana": ["Lissandra", "Annie", "Malzahar"],
    "Ryze": ["Fizz", "Zed", "LeBlanc"],
    "Swain": ["Viktor", "Cassiopeia", "Xerath"], 
    "Sylas": ["Lissandra", "Annie", "Malzahar"],
    "Syndra": ["Fizz", "LeBlanc", "Zed"],
    "Taliyah": ["Zed", "Fizz", "LeBlanc"], 
    "Talon": ["Lissandra", "Annie", "Malzahar"],
    "Twisted Fate": ["Fizz", "Zed", "LeBlanc"],
    "Veigar": ["Fizz", "Zed", "LeBlanc"],
    "Vel'Koz": ["Fizz", "LeBlanc", "Talon"],
    "Vex": ["Fizz", "Zed", "LeBlanc"],
    "Viktor": ["Fizz", "Zed", "LeBlanc"],
    "Vladimir": ["Cassiopeia", "Annie", "Malzahar"],
    "Xerath": ["Fizz", "Zed", "LeBlanc"],
    "Yasuo": ["Malphite", "Lissandra", "Annie"],
    "Yone": ["Malphite", "Lissandra", "Annie"],
    "Zed": ["Malzahar", "Lissandra", "Annie"],
    "Ziggs": ["Fizz", "Zed", "LeBlanc"],
    "Zoe": ["Fizz", "LeBlanc", "Zed"],
    "Mel": ["LeBlanc", "Zed", "Kassadin"],

    # --- JUNGLE ---
    "Amumu": ["Olaf", "Trundle", "Morgana"],
    "Bel'Veth": ["Warwick", "Udyr", "Trundle"],
    "Briar": ["Trundle", "Udyr", "Warwick"],
    "Elise": ["Graves", "Lee Sin", "Olaf"],
    "Evelynn": ["Lee Sin", "Rek'Sai", "Rengar"],
    "Fiddlesticks": ["Evelynn", "Morgana", "Nocturne"],
    "Gragas": ["Olaf", "Trundle", "Graves"], 
    "Graves": ["Trundle", "Udyr", "Warwick"],
    "Hecarim": ["Trundle", "Udyr", "Sejuani"],
    "Ivern": ["Graves", "Kindred", "Nidalee"],
    "Jarvan IV": ["Trundle", "Olaf", "Poppy"],
    "Karthus": ["Evelynn", "Rengar", "Lee Sin"],
    "Kayn": ["Trundle", "Udyr", "Warwick"],
    "Kha'Zix": ["Lee Sin", "Rengar", "Rek'Sai"],
    "Kindred": ["Lee Sin", "Graves", "Kha'Zix"],
    "Lee Sin": ["Trundle", "Udyr", "Warwick"],
    "Lillia": ["Graves", "Kindred", "Rengar"],
    "Master Yi": ["Jax", "Udyr", "Warwick"],
    "Maokai": ["Trundle", "Olaf", "Udyr"],
    "Nidalee": ["Graves", "Lee Sin", "Kindred"],
    "Nocturne": ["Warwick", "Trundle", "Udyr"], 
    "Nunu & Willump": ["Trundle", "Olaf", "Warwick"], 
    "Olaf": ["Trundle", "Warwick", "Udyr"],
    "Rammus": ["Trundle", "Udyr", "Olaf"],
    "Rek'Sai": ["Trundle", "Warwick", "Udyr"],
    "Rengar": ["Lee Sin", "Rek'Sai", "Trundle"],
    "Sejuani": ["Trundle", "Olaf", "Warwick"],
    "Shaco": ["Lee Sin", "Rengar", "Rek'Sai"],
    "Shyvana": ["Trundle", "Warwick", "Udyr"],
    "Skarner": ["Trundle", "Udyr", "Morgana"],
    "Udyr": ["Trundle", "Warwick", "Lee Sin"],
    "Vi": ["Trundle", "Olaf", "Sejuani"],
    "Viego": ["Trundle", "Udyr", "Warwick"],
    "Warwick": ["Trundle", "Kindred", "Olaf"],
    "Wukong": ["Trundle", "Udyr", "Warwick"],
    "Xin Zhao": ["Trundle", "Udyr", "Olaf"],
    "Zac": ["Trundle", "Warwick", "Olaf"],
    "Nunu e Willump": ["Trundle", "Olaf", "Warwick"],

    # --- BOT LANE (ADC) ---
    "Aphelios": ["Draven", "Caitlyn", "Lucian"],
    "Ashe": ["Miss Fortune", "Sivir", "Jhin"],
    "Caitlyn": ["Draven", "Lucian", "Samira"],
    "Draven": ["Lucian", "Caitlyn", "Samira"],
    "Ezreal": ["Draven", "Lucian", "Caitlyn"],
    "Jhin": ["Caitlyn", "Draven", "Lucian"],
    "Jinx": ["Caitlyn", "Draven", "Lucian"],
    "Kai'Sa": ["Caitlyn", "Draven", "Lucian"],
    "Kalista": ["Caitlyn", "Draven", "Samira"],
    "Kog'Maw": ["Draven", "Caitlyn", "Lucian"],
    "Lucian": ["Draven", "Samira", "Caitlyn"],
    "Miss Fortune": ["Lucian", "Draven", "Samira"],
    "Nilah": ["Draven", "Lucian", "Samira"],
    "Samira": ["Leona", "Nautilus", "Alistar"], 
    "Sivir": ["Caitlyn", "Draven", "Lucian"],
    "Smolder": ["Caitlyn", "Draven", "Lucian"],
    "Tristana": ["Caitlyn", "Draven", "Lucian"],
    "Twitch": ["Caitlyn", "Draven", "Lucian"],
    "Varus": ["Caitlyn", "Draven", "Lucian"],
    "Vayne": ["Caitlyn", "Draven", "Samira"],
    "Xayah": ["Draven", "Lucian", "Caitlyn"],
    "Zeri": ["Caitlyn", "Draven", "Lucian"],

    # --- SUPPORT ---
    "Alistar": ["Janna", "Morgana", "Zilean"],
    "Bard": ["Brand", "Zyra", "Morgana"], 
    "Blitzcrank": ["Morgana", "Janna", "Thresh"],
    "Brand": ["Blitzcrank", "Leona", "Nautilus"], 
    "Braum": ["Sona", "Morgana", "Zyra"],
    "Janna": ["Blitzcrank", "Leona", "Pyke"],
    "Karma": ["Brand", "Zyra", "Vel'Koz"],
    "Leona": ["Morgana", "Janna", "Lulu"],
    "Lulu": ["Blitzcrank", "Leona", "Nautilus"],
    "Milio": ["Blitzcrank", "Nautilus", "Pyke"],
    "Morgana": ["Blitzcrank", "Leona", "Nautilus"],
    "Nami": ["Zyra", "Brand", "Vel'Koz"],
    "Nautilus": ["Morgana", "Janna", "Lulu"],
    "Pyke": ["Morgana", "Janna", "Thresh"],
    "Rakan": ["Morgana", "Janna", "Lulu"],
    "Rell": ["Morgana", "Janna", "Zyra"],
    "Renata Glasc": ["Blitzcrank", "Nautilus", "Pyke"],
    "Senna": ["Blitzcrank", "Leona", "Nautilus"],
    "Seraphine": ["Zyra", "Brand", "Vel'Koz"],
    "Sona": ["Brand", "Zyra", "Vel'Koz"],
    "Soraka": ["Blitzcrank", "Leona", "Pyke"],
    "Swain (Support)": ["Viktor", "Cassiopeia", "Xerath"],
    "Taric": ["Brand", "Vel'Koz", "Zyra"],
    "Thresh": ["Morgana", "Janna", "Lulu"],
    "Yuumi": ["Blitzcrank", "Leona", "Pyke"],
    "Zilean": ["Blitzcrank", "Leona", "Nautilus"],
    "Zyra": ["Brand", "Vel'Koz", "Xerath"],
    "Bardo": ["Brand", "Zyra", "Blitzcrank"],

}


@router.get("/counters") # criando endpoint 
def get_all_counters():
    return COUNTERS


# uvicorn API_counter:app --reload