from fastapi import APIRouter

router = APIRouter()

ADVANTAGES = {
    # --- TOP LANE ---
    "Aatrox": ["Garen", "Mordekaiser", "Dr. Mundo"],
    "Camille": ["Aatrox", "Gangplank", "Gnar"],
    "Cho'Gath": ["Malphite", "Dr. Mundo", "Sion"],
    "Darius": ["Garen", "Kayle", "Ornn"],
    "Dr. Mundo": ["Malphite", "Ornn", "Maokai"],
    "Fiora": ["Aatrox", "Cho'Gath", "Garen"],
    "Gangplank": ["Ornn", "Sion", "Gnar"],
    "Garen": ["Irelia", "Quinn", "Riven"],
    "Gnar": ["Sett", "Darius", "Singed"],
    "Gwen": ["Dr. Mundo", "Mordekaiser", "Ornn"],
    "Illaoi": ["Dr. Mundo", "Nasus", "Tahm Kench"],
    "Irelia": ["Gangplank", "Gnar", "Kayle"],
    "Jax": ["Aatrox", "Gangplank", "Master Yi"],
    "Jayce": ["Gnar", "Rumble", "Kennen"],
    "Kayle": ["Cho'Gath", "Darius", "Gwen"],
    "Kennen": ["Gnar", "Quinn", "Singed"],
    "Kled": ["Aatrox", "Camille", "Fiora"],
    "K'Sante": ["Malphite", "Gnar", "Ornn"],
    "Malphite": ["Camille", "Fiora", "Irelia"],
    "Mordekaiser": ["Garen", "Dr. Mundo", "Sion"],
    "Nasus": ["Dr. Mundo", "Malphite", "Shen"],
    "Olaf": ["Dr. Mundo", "Amumu", "Elise"],
    "Ornn": ["Kennen", "Malphite", "Teemo"],
    "Pantheon": ["Yasuo", "Yone", "Tryndamere"],
    "Poppy": ["Jarvan IV", "Garen", "Riven"],
    "Quinn": ["Camille", "Darius", "Fiora"],
    "Renekton": ["Kayle", "Riven", "Yasuo"],
    "Riven": ["Kayle", "Yasuo", "Yone"],
    "Rumble": ["Garen", "Darius", "Nasus"],
    "Sett": ["Irelia", "Yasuo", "Yone"],
    "Shen": ["Jax", "Tryndamere", "Renekton"],
    "Singed": ["Darius", "Garen", "Sett"],
    "Sion": ["Kennen", "Quinn", "Teemo"],
    "Tahm Kench": ["Malphite", "Ornn", "Sion"],
    "Teemo": ["Camille", "Darius", "Fiora"],
    "Tryndamere": ["Kayle", "Gwen", "Shen"],
    "Trundle": ["Amumu", "Bel'Veth", "Briar"],
    "Urgot": ["Gnar", "Malphite", "Yasuo"],
    "Vayne": ["Cho'Gath", "Dr. Mundo", "Gwen"],
    "Volibear": ["Garen", "Sett", "Irelia"],
    "Yorick": ["Shen", "Ornn", "Malphite"],
    "Ambessa":  ["Malphite", "Teemo", "Riven"],

    # --- MID LANE ---
    "Ahri": ["Viktor", "Syndra", "Twisted Fate"],
    "Akali": ["Veigar", "Xerath", "Lux"],
    "Akshan": ["Viktor", "Veigar", "Zoe"],
    "Anivia": ["Cassiopeia", "Ryze", "Vladimir"],
    "Annie": ["Akali", "Fizz", "Katarina"],
    "Aurelion Sol": ["Ryze", "Viktor", "Cassiopeia"],
    "Aurora": ["Ryze", "Viktor", "Veigar"],
    "Azir": ["Cassiopeia", "Viktor", "Ryze"],
    "Cassiopeia": ["Vladimir", "Swain", "Sylas"],
    "Corki": ["Azir", "Ryze", "Twisted Fate"],
    "Diana": ["Lux", "Veigar", "Xerath"],
    "Ekko": ["Lux", "Veigar", "Xerath"],
    "Fizz": ["Anivia", "Aurelion Sol", "Diana"],
    "Galio": ["Katarina", "Akali", "Ekko"],
    "Heimerdinger": ["Fizz", "Zed", "Akali"],
    "Hwei": ["Aurelion Sol", "Viktor", "Veigar"],
    "Kassadin": ["Galio", "Veigar", "Viktor"],
    "Katarina": ["Anivia", "Neeko", "Veigar"],
    "LeBlanc": ["Ahri", "Aurelion Sol", "Ekko"],
    "Lissandra": ["Akali", "Fizz", "Katarina"],
    "Lux": ["Ryze", "Orianna", "Viktor"],
    "Malzahar": ["Katarina", "LeBlanc", "Qiyana"],
    "Naafiri": ["Lux", "Veigar", "Ahri"],
    "Neeko": ["Ahri", "Lux", "Veigar"],
    "Orianna": ["Ryze", "Cassiopeia", "Sylas"],
    "Qiyana": ["Lux", "Veigar", "Xerath"],
    "Ryze": ["Aurelion Sol", "Veigar", "Viktor"],
    "Swain": ["Cassiopeia", "Lissandra", "Viktor"],
    "Sylas": ["Lux", "Veigar", "Xerath"],
    "Syndra": ["Heimerdinger", "Veigar", "Viktor"],
    "Taliyah": ["Lux", "Veigar", "Xerath"],
    "Talon": ["Ahri", "Aurelion Sol", "Diana"],
    "Twisted Fate": ["Ryze", "Sylas", "Viktor"],
    "Veigar": ["Galio", "Ryze", "Orianna"],
    "Vel'Koz": ["Annie", "Lissandra", "Karma"],
    "Vex": ["Fizz", "Yasuo", "Yone"],
    "Viktor": ["Cassiopeia", "Swain", "Ryze"],
    "Vladimir": ["Lux", "Veigar", "Viktor"],
    "Xerath": ["Annie", "Lissandra", "Swain (Support)"],
    "Yasuo": ["Ahri", "Zoe", "Veigar"],
    "Yone": ["Ahri", "Zoe", "Veigar"],
    "Zed": ["Ahri", "Anivia", "Aurelion Sol"],
    "Ziggs": ["Annie", "Lissandra", "Heimerdinger"],
    "Zoe": ["Lux", "Viktor", "Veigar"],
    "Ambessa":  ["Yasuo", "Ahri", "Twisted Fate"],

    # --- JUNGLE ---
    "Amumu": ["Master Yi", "Kindred", "Graves"],
    "Bel'Veth": ["Karthus", "Evelynn", "Amumu"],
    "Briar": ["Evelynn", "Karthus", "Lillia"],
    "Elise": ["Master Yi", "Nocturne", "Zac"],
    "Evelynn": ["Fiddlesticks", "Karthus", "Amumu"],
    "Fiddlesticks": ["Master Yi", "Kindred", "Graves"],
    "Gragas": ["Elise", "Master Yi", "Kindred"],
    "Graves": ["Elise", "Gragas", "Ivern"],
    "Hecarim": ["Karthus", "Lillia", "Evelynn"],
    "Ivern": ["Rammus", "Amumu", "Sejuani"],
    "Jarvan IV": ["Master Yi", "Evelynn", "Karthus"],
    "Karthus": ["Sejuani", "Zac", "Amumu"],
    "Kayn": ["Amumu", "Karthus", "Evelynn"],
    "Kha'Zix": ["Kindred", "Amumu", "Evelynn"],
    "Kindred": ["Ivern", "Lillia", "Warwick"],
    "Lee Sin": ["Elise", "Evelynn", "Karthus"],
    "Lillia": ["Zac", "Sejuani", "Amumu"],
    "Master Yi": ["Amumu", "Sejuani", "Skarner"],
    "Maokai": ["Kindred", "Graves", "Nocturne"],
    "Nidalee": ["Ivern", "Amumu", "Sejuani"],
    "Nocturne": ["Fiddlesticks", "Amumu", "Karthus"],
    "Nunu & Willump": ["Master Yi", "Kindred", "Graves"],
    "Rammus": ["Master Yi", "Kindred", "Graves"],
    "Rek'Sai": ["Evelynn", "Kha'Zix", "Rengar"],
    "Rengar": ["Evelynn", "Karthus", "Lillia"],
    "Sejuani": ["Hecarim", "Vi", "Master Yi"],
    "Shaco": ["Amumu", "Sejuani", "Karthus"],
    "Shyvana": ["Amumu", "Sejuani", "Zac"],
    "Skarner": ["Master Yi", "Kindred", "Graves"],
    "Udyr": ["Bel'Veth", "Graves", "Hecarim"],
    "Vi": ["Evelynn", "Karthus", "Lillia"],
    "Viego": ["Karthus", "Evelynn", "Amumu"],
    "Warwick": ["Bel'Veth", "Graves", "Kayn"],
    "Wukong": ["Amumu", "Karthus", "Evelynn"],
    "Xin Zhao": ["Amumu", "Karthus", "Evelynn"],
    "Zac": ["Master Yi", "Kindred", "Graves"],
    "Nunu e Willump": ["Master Yi", "Kindred", "Evelynn"],

    # --- BOT LANE (ADC) ---
    "Aphelios": ["Ashe", "Jinx", "Kog'Maw"],
    "Ashe": ["Kog'Maw", "Vayne", "Twitch"],
    "Caitlyn": ["Aphelios", "Draven", "Ezreal"],
    "Draven": ["Aphelios", "Caitlyn", "Ezreal"],
    "Ezreal": ["Ashe", "Jinx", "Sivir"],
    "Jhin": ["Ashe", "Kog'Maw", "Vayne"],
    "Jinx": ["Ashe", "Kog'Maw", "Vayne"],
    "Kai'Sa": ["Ashe", "Jinx", "Kog'Maw"],
    "Kalista": ["Ashe", "Kog'Maw", "Jinx"],
    "Kog'Maw": ["Ashe", "Jinx", "Sivir"],
    "Lucian": ["Aphelios", "Ezreal", "Jhin"],
    "Miss Fortune": ["Ashe", "Jinx", "Kog'Maw"],
    "Nilah": ["Ashe", "Jinx", "Kog'Maw"],
    "Samira": ["Caitlyn", "Draven", "Kalista"],
    "Sivir": ["Ashe", "Jinx", "Kog'Maw"],
    "Smolder": ["Ashe", "Jinx", "Kog'Maw"],
    "Tristana": ["Ashe", "Jinx", "Kog'Maw"],
    "Twitch": ["Ashe", "Jinx", "Kog'Maw"],
    "Varus": ["Ashe", "Jinx", "Kog'Maw"],
    "Vayne": ["Ashe", "Jinx", "Sivir"],
    "Xayah": ["Ashe", "Jinx", "Kog'Maw"],
    "Zeri": ["Ashe", "Jinx", "Kog'Maw"],

    # --- SUPPORT ---
    "Alistar": ["Samira", "Tristana", "Nilah"],
    "Bard": ["Soraka", "Sona", "Yuumi"],
    "Blitzcrank": ["Janna", "Lulu", "Milio"],
    "Brand": ["Bard", "Karma", "Nami"],
    "Braum": ["Ezreal", "Lucian", "Caitlyn"],
    "Janna": ["Alistar", "Leona", "Nautilus"],
    "Karma": ["Sona", "Soraka", "Braum"],
    "Leona": ["Janna", "Lulu", "Milio"],
    "Lulu": ["Leona", "Nautilus", "Rakan"],
    "Milio": ["Soraka", "Sona", "Yuumi"],
    "Morgana": ["Alistar", "Bard", "Braum"],
    "Nami": ["Sona", "Soraka", "Braum"],
    "Nautilus": ["Lulu", "Milio", "Renata Glasc"],
    "Pyke": ["Janna", "Milio", "Renata Glasc"],
    "Rakan": ["Braum", "Tahm Kench", "Taric"],
    "Rell": ["Sona", "Soraka", "Yuumi"],
    "Renata Glasc": ["Sona", "Soraka", "Yuumi"],
    "Senna": ["Sona", "Soraka", "Yuumi"],
    "Seraphine": ["Sona", "Soraka", "Yuumi"],
    "Sona": ["Braum", "Taric", "Tahm Kench"],
    "Soraka": ["Braum", "Taric", "Tahm Kench"],
    "Swain (Support)": ["Sona", "Soraka", "Yuumi"],
    "Taric": ["Leona", "Nautilus", "Alistar"],
    "Thresh": ["Blitzcrank", "Pyke", "Braum"],
    "Yuumi": ["Ezreal", "Sivir", "Zeri"], 
    "Zilean": ["Alistar", "Sona", "Soraka"],
    "Zyra": ["Bard", "Braum", "Karma"],
    "Bardo": ["Soraka", "Sona", "Braum"],
}


@router.get("/advantages") # criando endpoint 
def get_all_advantages():
    return ADVANTAGES


# uvicorn API_counter:app --reload